# Generated by Django 4.0.1 on 2022-01-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=120)),
                ('name_en_1', models.CharField(max_length=120)),
                ('spell_1', models.CharField(max_length=120)),
                ('name_en_2', models.CharField(max_length=120)),
                ('spell_2', models.CharField(max_length=120)),
                ('name_en_3', models.CharField(max_length=120)),
                ('spell_3', models.CharField(max_length=120)),
            ],
        ),
    ]
