# Generated by Django 4.0.1 on 2022-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event data'),
        ),
        migrations.AddField(
            model_name='event',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='Describe'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title event'),
        ),
        migrations.DeleteModel(
            name='MySiteUser',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
