# Generated by Django 4.0.1 on 2022-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_remove_event_attendees_remove_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date_post', models.DateTimeField()),
                ('text', models.TextField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Event data'),
        ),
    ]
